let j = [ { original_name: "Marvel's The Punisher",
    id: 67178,
    name: "Marvel's The Punisher",
    vote_count: 363,
    vote_average: 8,
    first_air_date: '2017-11-17',
    poster_path: '/s2YM9zHF3tf2coi8t0UEzYrOHg8.jpg',
    genre_ids: [ 80, 18, 10759 ],
    original_language: 'en',
    backdrop_path: '/sRr5NdPic882T24dNwkiw2VMst6.jpg',
    overview:
     "A former Marine out to punish the criminals responsible for his family's murder finds himself ensnared in a military conspiracy.",
    origin_country: [ 'US' ],
    popularity: 92.216 },
  { original_name: 'Star Trek: Discovery',
    id: 67198,
    name: 'Star Trek: Discovery',
    vote_count: 453,
    vote_average: 6.8,
    first_air_date: '2017-09-24',
    poster_path: '/aJTSeqG43514TewIuS9hiHvbero.jpg',
    genre_ids: [ 10765 ],
    original_language: 'en',
    backdrop_path: '/rhE2h8WYJOPuBlMl20MQRnJw3aq.jpg',
    overview:
     'Follow the voyages of Starfleet on their missions to discover new worlds and new life forms, and one Starfleet officer who must learn that to truly understand all things alien, you must first understand yourself.',
    origin_country: [ 'US' ],
    popularity: 119.921 },
  { original_name: 'True Detective',
    id: 46648,
    name: 'True Detective',
    vote_count: 1010,
    vote_average: 8.2,
    first_air_date: '2014-01-12',
    poster_path: '/aowr4xpLP5sRCL50TkuADomJ98T.jpg',
    genre_ids: [ 18 ],
    original_language: 'en',
    backdrop_path: '/2Ahm0YjLNQKuzSf9LOkHrXk8qIE.jpg',
    overview:
     'An American anthology police detective series utilizing multiple timelines in which investigations seem to unearth personal and professional secrets of those involved, both within or outside the law.',
    origin_country: [ 'US' ],
    popularity: 82.406 },
  { original_name: 'Wayne',
    id: 84231,
    name: 'Wayne',
    vote_count: 2,
    vote_average: 6,
    first_air_date: '2019-01-16',
    poster_path: '/jPjHpQwJ3yew7ZlqHry8UDiVDgj.jpg',
    genre_ids: [ 18 ],
    original_language: 'en',
    backdrop_path: '/5LTKU79rIPu8ivXJhR6rSyj6t8w.jpg',
    overview:
     'In this gritty and sometimes bloody tale, sixteen year-old Wayne sets out on a dirt bike with his new crush Del to take back the 1978 Pontiac Trans Am that was stolen from his father before he died. It is Wayne and Del against the world.',
    origin_country: [ 'US' ],
    popularity: 23.724 },
  { original_name: 'Game of Thrones',
    id: 1399,
    name: 'Game of Thrones',
    vote_count: 5182,
    vote_average: 8.2,
    first_air_date: '2011-04-17',
    poster_path: '/gwPSoYUHAKmdyVywgLpKKA4BjRr.jpg',
    genre_ids: [ 18, 10759, 10765 ],
    original_language: 'en',
    backdrop_path: '/gX8SYlnL9ZznfZwEH4KJUePBFUM.jpg',
    overview:
     "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    origin_country: [ 'US' ],
    popularity: 198.323 },
  { original_name: 'Outlander',
    id: 56570,
    name: 'Outlander',
    vote_count: 439,
    vote_average: 7.2,
    first_air_date: '2014-08-09',
    poster_path: '/ioQ0o7dOU6AD8gKIHHPX0czqgSw.jpg',
    genre_ids: [ 12, 18, 14, 10749 ],
    original_language: 'en',
    backdrop_path: '/qutOe29dCGmT2JUlLPCqlzaQIo.jpg',
    overview:
     "The story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened. When she is forced to marry Jamie, a chivalrous and romantic young Scottish warrior, a passionate affair is ignited that tears Claire's heart between two vastly different men in two irreconcilable lives.",
    origin_country: [ 'US' ],
    popularity: 118.168 },
  { original_name: 'Sex Education',
    id: 81356,
    name: 'Sex Education',
    vote_count: 25,
    vote_average: 7.7,
    first_air_date: '2019-01-11',
    poster_path: '/dH7ua9OMVQQsaDssVGKx8WiK1IR.jpg',
    genre_ids: [ 35, 18 ],
    original_language: 'en',
    backdrop_path: '/u23G9KZregWHs1use6ir1fX27gl.jpg',
    overview:
     'Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school.',
    origin_country: [ 'GB', 'US' ],
    popularity: 208.881 },
  { original_name: 'Vikings',
    id: 44217,
    name: 'Vikings',
    vote_count: 1509,
    vote_average: 7.4,
    first_air_date: '2013-03-03',
    poster_path: '/94gP9uXNdbypwCLORjeurlad15Z.jpg',
    genre_ids: [ 18, 10759 ],
    original_language: 'en',
    backdrop_path: '/A30ZqEoDbchvE7mCZcSp6TEwB1Q.jpg',
    overview:
     "Vikings follows the adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.",
    origin_country: [ 'CA' ],
    popularity: 264.242 },
  { original_name: 'Grace and Frankie',
    id: 62320,
    name: 'Grace and Frankie',
    vote_count: 74,
    vote_average: 7.5,
    first_air_date: '2015-05-08',
    poster_path: '/3aD3PaSeF8eHJFLliLlWYw4EcPt.jpg',
    genre_ids: [ 35, 18 ],
    original_language: 'en',
    backdrop_path: '/nYHYqizKJNQwdVE2Y485rbtvk4O.jpg',
    overview:
     'Elegant, proper Grace and freewheeling, eccentric Frankie are a pair of frenemies whose lives are turned upside down - and permanently intertwined - when their husbands leave them for each other. Together, they must face starting over in their 70s in a 21st century world.',
    origin_country: [ 'US' ],
    popularity: 38.148 },
  { original_name: 'Supergirl',
    id: 62688,
    name: 'Supergirl',
    vote_count: 830,
    vote_average: 5.8,
    first_air_date: '2015-10-26',
    poster_path: '/vqBsgL9nd2v04ZvCqPzwtckDdFD.jpg',
    genre_ids: [ 28, 12, 18, 878 ],
    original_language: 'en',
    backdrop_path: '/2qou2R47XZ1N6SlqGZcoCHDyEhN.jpg',
    overview:
     'Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.',
    origin_country: [ 'US' ],
    popularity: 118.895 },
  { original_name: 'The Grand Tour',
    id: 67557,
    name: 'The Grand Tour',
    vote_count: 261,
    vote_average: 7.8,
    first_air_date: '2016-11-18',
    poster_path: '/4bRY1FiDcLnpwJAELYOLinL3fIp.jpg',
    genre_ids: [ 99 ],
    original_language: 'en',
    backdrop_path: '/qnmd44b2gPFxZTEZ8CG0fyOgKjD.jpg',
    overview:
     "Jeremy Clarkson, Richard Hammond and James May are back with a show about adventure, excitement and friendship... as long as you accept that the people you call friends are also the ones you find extremely annoying. Sometimes it's even a show about cars. Follow them on their global adventure.",
    origin_country: [ 'GB' ],
    popularity: 81.52 },
  { original_name: 'Riverdale',
    id: 69050,
    name: 'Riverdale',
    vote_count: 405,
    vote_average: 7.1,
    first_air_date: '2017-01-26',
    poster_path: '/gskv297rlbyzLaTU1XZf8UBbxp0.jpg',
    genre_ids: [ 18, 9648 ],
    original_language: 'en',
    backdrop_path: '/2IUpoKSP64r6rp2vBo0Fdk8a1UU.jpg',
    overview:
     'Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.',
    origin_country: [ 'US' ],
    popularity: 196.086 },
  { original_name: 'Shameless',
    id: 34307,
    name: 'Shameless',
    vote_count: 762,
    vote_average: 7.9,
    first_air_date: '2011-01-09',
    poster_path: '/iRyQTp2L437k6zfFCvZSOWaxQFA.jpg',
    genre_ids: [ 35, 18 ],
    original_language: 'en',
    backdrop_path: '/zjOj2gnDJYFdYt6R7FtuHn7yrPr.jpg',
    overview:
     "Chicagoan Frank Gallagher is the proud single dad of six smart, industrious, independent kids, who without him would be... perhaps better off. When Frank's not at the bar spending what little money they have, he's passed out on the floor. But the kids have found ways to grow up in spite of him. They may not be like any family you know, but they make no apologies for being exactly who they are.",
    origin_country: [ 'US' ],
    popularity: 102.036 },
  { original_name: 'The Big Bang Theory',
    id: 1418,
    name: 'The Big Bang Theory',
    vote_count: 3520,
    vote_average: 6.8,
    first_air_date: '2007-09-24',
    poster_path: '/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg',
    genre_ids: [ 35 ],
    original_language: 'en',
    backdrop_path: '/nGsNruW3W27V6r4gkyc3iiEGsKR.jpg',
    overview:
     "The Big Bang Theory is centered on five characters living in Pasadena, California: roommates Leonard Hofstadter and Sheldon Cooper; Penny, a waitress and aspiring actress who lives across the hall; and Leonard and Sheldon's equally geeky and socially awkward friends and co-workers, mechanical engineer Howard Wolowitz and astrophysicist Raj Koothrappali. The geekiness and intellect of the four guys is contrasted for comic effect with Penny's social skills and common sense.",
    origin_country: [ 'US' ],
    popularity: 135.525 },
  { original_name: "Grey's Anatomy",
    id: 1416,
    name: "Grey's Anatomy",
    vote_count: 839,
    vote_average: 6.3,
    first_air_date: '2005-03-27',
    poster_path: '/mgOZSS2FFIGtfVeac1buBw3Cx5w.jpg',
    genre_ids: [ 18 ],
    original_language: 'en',
    backdrop_path: '/y6JABtgWMVYPx84Rvy7tROU5aNH.jpg',
    overview:
     'Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.',
    origin_country: [ 'US' ],
    popularity: 140.761 },
  { original_name: 'Brooklyn Nine-Nine',
    id: 48891,
    name: 'Brooklyn Nine-Nine',
    vote_count: 516,
    vote_average: 7.6,
    first_air_date: '2013-09-17',
    poster_path: '/kSvVRYB4WGGueigKOENClUSq8N2.jpg',
    genre_ids: [ 35, 80 ],
    original_language: 'en',
    backdrop_path: '/ncC9ZgZuKOdaVm7yXinUn26Qyok.jpg',
    overview:
     'A single-camera ensemble comedy following the lives of an eclectic group of detectives in a New York precinct, including one slacker who is forced to shape up when he gets a new boss.',
    origin_country: [ 'US' ],
    popularity: 117.386 },
  { original_name: 'Future Man',
    id: 73157,
    name: 'Future Man',
    vote_count: 68,
    vote_average: 7.3,
    first_air_date: '2017-11-14',
    poster_path: '/9P72cymABXbQKaOUBdZf6pOW64e.jpg',
    genre_ids: [ 35, 10765 ],
    original_language: 'en',
    backdrop_path: '/qQxb3uVa3mhZ1pFY2DlmtdKreXd.jpg',
    overview:
     'Josh Futturman, a janitor by day/world-ranked gamer by night, is tasked with preventing the extinction of humanity after mysterious visitors from the future proclaim him the key to defeating the imminent super-race invasion.',
    origin_country: [ 'US' ],
    popularity: 178.249 },
  { original_name: 'Titans',
    id: 75450,
    name: 'Titans',
    vote_count: 82,
    vote_average: 6.9,
    first_air_date: '2018-10-12',
    poster_path: '/oCK6fykCZUQjTJG4IDhfWCxcXqG.jpg',
    genre_ids: [ 18, 10759, 10765 ],
    original_language: 'en',
    backdrop_path: '/9foO1E8sliKN2dvtMOEwwQgynlW.jpg',
    overview:
     "A team of young superheroes led by Nightwing (formerly Batman's first Robin) form to combat evil and other perils.",
    origin_country: [ 'US' ],
    popularity: 110.93 },
  { original_name: 'Blindspot',
    id: 62710,
    name: 'Blindspot',
    vote_count: 561,
    vote_average: 6.3,
    first_air_date: '2015-09-21',
    poster_path: '/iAkEexatzMUlCXlbS8Gmvlic9gQ.jpg',
    genre_ids: [ 28, 80, 18 ],
    original_language: 'en',
    backdrop_path: '/ioBqBeEN5QmNwKp37kf6ohkmJKy.jpg',
    overview:
     `A vast international plot explodes when a beautiful Jane Doe is discovered naked in Times Square, completely covered in mysterious, intricate tattoos with no memory of who she is or how she got there. But there's one tattoo that is impossible to miss: the name of FBI agent Kurt Weller, emblazoned across her back. "Jane," Agent Weller and the rest of the FBI quickly realize that each mark on her body is a crime to solve, leading them closer to the truth about her identity and the mysteries to be revealed.`,
    origin_country: [ 'US' ],
    popularity: 79.103 },
  { original_name: 'Counterpart',
    id: 63646,
    name: 'Counterpart',
    vote_count: 72,
    vote_average: 6.7,
    first_air_date: '2017-12-10',
    poster_path: '/vBIc9SkfZUUUUYD5b9srR5NpX5o.jpg',
    genre_ids: [ 18, 878 ],
    original_language: 'en',
    backdrop_path: '/b92ZXORrpljn3YRAXOrURhVO0JV.jpg',
    overview:
     'Howard Silk is a lowly cog in a bureaucratic UN agency who is turning the last corner of a life filled with regret when he discovers the agency he works for is guarding a secret: a crossing to a parallel dimension.',
    origin_country: [ 'US' ],
    popularity: 42.862 } ]


for (let i = 0; i < 10; i++) {
    const title = j[i].original_name;
    const posterPath = j[i].poster_path;
    const overview = j[i].overview;
    const voteScore = j[i].vote_average;
    const releaseDate = j[i].first_air_date;
    console.log(title, posterPath, overview, voteScore, releaseDate);
}

